"""updated  made model for user

Revision ID: 226cbfc3e5d3
Revises: b7ff140472d0
Create Date: 2023-08-03 15:06:40.755443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226cbfc3e5d3'
down_revision = 'b7ff140472d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
