"""updated  made model for user

Revision ID: 376e03bbfb8c
Revises: 226cbfc3e5d3
Create Date: 2023-08-03 15:07:23.730957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376e03bbfb8c'
down_revision = '226cbfc3e5d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
