"""updated  made model for user

Revision ID: 5589f0b16c85
Revises: a028b5de5163
Create Date: 2023-08-03 15:09:48.864413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5589f0b16c85'
down_revision = 'a028b5de5163'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
